### ISSUE TITLE
alanning:roles schema

### ISSUE THREAD

**Issue by alanning** [yathit/meteor-roles-migrate#1]
Hi @yathit,

I am the maintainer of alanning:roles and ran across your migration repo.  Was curious to hear more about what was lacking in alanning:roles that made you want to change.

For reference, you can give users roles such as "canvas.add" and if you don't use groups, the database schema will be:

```
{
  roles: ["canvas.add"]
}
```

**Comment by yathit** [comment]
Hi @alanning migration is required due to [orion package](https://atmospherejs.com/orionjs/core). 

Right, otherwise, I will prefer alanning:roles for scalability and performance reason.

**Comment by alanning** [comment]
Thanks for the link, I'll check out the orion package too.

Feel free to let me know via an issue on https://github.com/alanning/meteor-roles/issues if there's anything we can do better.
